### ISSUE TITLE
gem install eth error

### ISSUE THREAD

**Issue by sai1024** [q9f/eth.rb#134]
hello,
ruby version: 3.0.3
my error:
```
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /Users/sai/.rvm/gems/ruby-3.0.3/gems/rbsecp256k1-5.1.0/ext/rbsecp256k1
/Users/sai/.rvm/rubies/ruby-3.0.3/bin/ruby -I /Users/sai/.rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0 -r ./siteconf20220707-73597-f0ln4m.rb extconf.rb
2 retrie(s) left for libsecp256k1.zip (Net::OpenTimeout)
1 retrie(s) left for libsecp256k1.zip (execution expired)
0 retrie(s) left for libsecp256k1.zip (execution expired)
execution expired
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/Users/sai/.rvm/rubies/ruby-3.0.3/bin/$(RUBY_BASE_NAME)
	--with-system-library
	--without-system-library
/Users/sai/.rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/digest.rb:50:in `initialize': No such file or directory @ rb_sysopen -
/Users/sai/.rvm/gems/ruby-3.0.3/gems/rbsecp256k1-5.1.0/ext/rbsecp256k1/ports/archives/libsecp256k1.zip (Errno::ENOENT)
	from /Users/sai/.rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/digest.rb:50:in `open'
	from /Users/sai/.rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/digest.rb:50:in `file'
	from /Users/sai/.rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/digest.rb:35:in `file'
	from /Users/sai/.rvm/gems/ruby-3.0.3/gems/mini_portile2-2.8.0/lib/mini_portile2/mini_portile.rb:335:in `verify_file'
	from extconf.rb:50:in `download'
	from /Users/sai/.rvm/gems/ruby-3.0.3/gems/mini_portile2-2.8.0/lib/mini_portile2/mini_portile.rb:182:in `cook'
	from extconf.rb:83:in `<main>'

extconf failed, exit code 1

Gem files will remain installed in /Users/sai/.rvm/gems/ruby-3.0.3/gems/rbsecp256k1-5.1.0 for inspection.
Results logged to /Users/sai/.rvm/gems/ruby-3.0.3/extensions/x86_64-darwin-18/3.0.0/rbsecp256k1-5.1.0/gem_make.out

  /Users/sai/.rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/rubygems/ext/builder.rb:93:in `run'
  /Users/sai/.rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/rubygems/ext/ext_conf_builder.rb:47:in `block in build'
  /Users/sai/.rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/tempfile.rb:317:in `open'
  /Users/sai/.rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/rubygems/ext/ext_conf_builder.rb:26:in `build'
  /Users/sai/.rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/rubygems/ext/builder.rb:159:in `build_extension'
  /Users/sai/.rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/rubygems/ext/builder.rb:193:in `block in build_extensions'
  /Users/sai/.rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/rubygems/ext/builder.rb:190:in `each'
  /Users/sai/.rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/rubygems/ext/builder.rb:190:in `build_extensions'
  /Users/sai/.rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/rubygems/installer.rb:845:in `build_extensions'
  /Users/sai/.rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/bundler/rubygems_gem_installer.rb:71:in `build_extensions'
  /Users/sai/.rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/bundler/rubygems_gem_installer.rb:28:in `install'
  /Users/sai/.rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/bundler/source/rubygems.rb:200:in `install'
  /Users/sai/.rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/bundler/installer/gem_installer.rb:54:in `install'
  /Users/sai/.rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/bundler/installer/gem_installer.rb:16:in `install_from_spec'
  /Users/sai/.rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/bundler/installer/parallel_installer.rb:186:in `do_install'
  /Users/sai/.rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/bundler/installer/parallel_installer.rb:177:in `block in worker_pool'
  /Users/sai/.rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/bundler/worker.rb:62:in `apply_func'
  /Users/sai/.rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/bundler/worker.rb:57:in `block in process_queue'
  /Users/sai/.rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/bundler/worker.rb:54:in `loop'
  /Users/sai/.rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/bundler/worker.rb:54:in `process_queue'
  /Users/sai/.rvm/rubies/ruby-3.0.3/lib/ruby/3.0.0/bundler/worker.rb:91:in `block (2 levels) in create_threads'

An error occurred while installing rbsecp256k1 (5.1.0), and Bundler cannot continue.

In Gemfile:
  eth was resolved to 0.5.6, which depends on
    rbsecp256k1
```

**Comment by sai1024** [comment]
ruby 2.6.6

```
Building native extensions. This could take a while...
ERROR:  Error installing eth:
	ERROR: Failed to build gem native extension.

    current directory: /Users/sai/.rvm/gems/ruby-2.6.6/gems/rbsecp256k1-5.1.0/ext/rbsecp256k1
/Users/sai/.rvm/rubies/ruby-2.6.6/bin/ruby -I /Users/sai/.rvm/rubies/ruby-2.6.6/lib/ruby/2.6.0 -r ./siteconf20220708-39813-l4r8ho.rb extconf.rb
2 retrie(s) left for libsecp256k1.zip (SSL_connect returned=1 errno=0 state=error: certificate verify failed (unspecified certificate verification error))
1 retrie(s) left for libsecp256k1.zip (execution expired)
0 retrie(s) left for libsecp256k1.zip (execution expired)
execution expired
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/Users/sai/.rvm/rubies/ruby-2.6.6/bin/$(RUBY_BASE_NAME)
	--with-system-library
	--without-system-library
/Users/sai/.rvm/rubies/ruby-2.6.6/lib/ruby/2.6.0/digest.rb:50:in `initialize': No such file or directory @ rb_sysopen - /Users/sai/.rvm/gems/ruby-2.6.6/gems/rbsecp256k1-5.1.0/ext/rbsecp256k1/ports/archives/libsecp256k1.zip (Errno::ENOENT)
	from /Users/sai/.rvm/rubies/ruby-2.6.6/lib/ruby/2.6.0/digest.rb:50:in `open'
	from /Users/sai/.rvm/rubies/ruby-2.6.6/lib/ruby/2.6.0/digest.rb:50:in `file'
	from /Users/sai/.rvm/rubies/ruby-2.6.6/lib/ruby/2.6.0/digest.rb:35:in `file'
	from /Users/sai/.rvm/gems/ruby-2.6.6/gems/mini_portile2-2.8.0/lib/mini_portile2/mini_portile.rb:335:in `verify_file'
	from extconf.rb:50:in `download'
	from /Users/sai/.rvm/gems/ruby-2.6.6/gems/mini_portile2-2.8.0/lib/mini_portile2/mini_portile.rb:182:in `cook'
	from extconf.rb:83:in `<main>'

extconf failed, exit code 1

Gem files will remain installed in /Users/sai/.rvm/gems/ruby-2.6.6/gems/rbsecp256k1-5.1.0 for inspection.
Results logged to /Users/sai/.rvm/gems/ruby-2.6.6/extensions/x86_64-darwin-18/2.6.0/rbsecp256k1-5.1.0/gem_make.out
```
