### ISSUE TITLE
empty access list bug

### ISSUE THREAD

**Issue by q9f** [q9f/eth.rb#51]
```
eth.sendRawTransaction("0x02f87282053980018504a817c800825208940c512b60531e2440edbee50f48bafdc6d291d8dd890246ddf9797668000080c080a075488ef7d2d6192758545f0020dd3e381a610068e6e7539860461ca25a952d38a0377b07f01be37bc1ebb48eb1ec9fa62c8e4ebf5c6b03d31a113b964b8c9e37e9")
Error: rlp: expected input list for types.txdata
	at web3.js:6347:37(47)
	at web3.js:5081:62(37)
	at <eval>:1:23(4)
```

https://ethereum.stackexchange.com/questions/119252/eip-2930-1559-is-an-empty-access-list-supposed-to-be-80-or-c0

**Comment by q9f** [comment]
my geth node was not supporting eip-1559
